### ISSUE TITLE
"Remember me" using localStorage

### ISSUE THREAD

**Issue by psvenk** [Aspine/aspine#112]
Add a "Remember me" checkbox to the login page which uses localStorage or browser cookies to store the username and password locally for convenience.

**Comment by tektaxi** [comment]
I wrote a first version of the remember me function. It's committed to my branch of the repo

**Comment by psvenk** [comment]
@tektaxi Thank you for your contribution. Would you be able to open a pull request from your repository so that we can do code review more easily? You should just be able to click "Pull request" from <https://github.com/tektaxi/aspine> and enter a description (if you put "Closes #112" in the description, GitHub will automatically close this issue when the pull request is merged) — please make sure that "allow edits from maintainers" is checked when you open the pull request.

**Comment by tektaxi** [comment]
@psvenk No problem. I added a pull request, let me know if I need to do something different with the code or requests etc.

**Comment by psvenk** [comment]
@tektaxi Thank you; I'll take a look now.
