### ISSUE TITLE
Some classes show the wrong assignments when switching terms

### ISSUE THREAD

**Issue by psvenk** [Aspine/aspine#113]
When I switch from "Current Quarter" (Q3) to Q2, one of my classes shows assignments from the second page of Q2 assignments and the second page of Q3 assignments, instead of showing the first and second page of Q2 assignments. I suspect that this is because Aspen "remembers" that it is on the second page (as it needed to scrape the second page of the "current" quarter after the first page) and gives the second page of Q3 assignments. Aspine's scraper also switches terms instead of trying to go to the next page for some reason or fills in "current quarter" data because it does not see any second page.

I am guessing that this bug can be fixed by having the scraper go back to the first page once done with scraping a class for some quarter.

**Comment by notrodes** [comment]
Sorry pressed wrong button
