### ISSUE TITLE
Schedule can't handle my wierd courseload

### ISSUE THREAD

**Issue by extrarude** [Aspine/aspine#13]

**Comment by maxtkc** [comment]
A little bit of context would be helpful.

**Comment by Ruborcalor** [comment]
I have attempted to fix the issue which I believe stemmed from your having more than 8 classes. The correction will be available in the next patch.

Even with this adjustment I wonder, are your classes in the right order?

**Comment by Ruborcalor** [comment]
We have pushed a fix for this issue. Could you please let us know how the schedule handles your weird courseload now?

**Comment by extrarude** [comment]
Mostly fixed. The last two PM courses still look like they're getting duplicated, listed as Period 4 the second time.
![screenshot 2019-02-27 at 11 15 01 am](https://user-images.githubusercontent.com/47579404/53505391-b6963400-3a81-11e9-83bd-2bf655386c37.png)
![screenshot 2019-02-27 at 11 14 36 am](https://user-images.githubusercontent.com/47579404/53505392-b6963400-3a81-11e9-9051-8d83decaeef3.png)

**Comment by Ruborcalor** [comment]
We greatly appreciate the follow up and the screenshots are great! We will try and implement a second fix tonight :).

**Comment by Ruborcalor** [comment]
We have followed up with a solution. The problem seems to be resolved so I will close the issue.

**Comment by Ruborcalor** [comment]
We have followed up with a solution. The problem seems to be resolved so I will close the issue.

**Comment by Ruborcalor** [comment]
We have followed up with a solution. The problem seems to be resolved so I will close the issue.
