### ISSUE TITLE
Getting 404 responses for some of the vendor resources on the login page

### ISSUE THREAD

**Issue by Ruborcalor** [Aspine/aspine#132]
![image](https://user-images.githubusercontent.com/47014480/91310708-35a41f80-e780-11ea-9eec-d1c06555faa7.png)

**Comment by psvenk** [comment]
Did you forget to run `npm install` after updating the repo?

**Comment by psvenk** [comment]
Sorry, please disregard my previous message. This is because `npm install` has not yet been run on the production server. I am trying to get this fixed.

**Comment by psvenk** [comment]
Should be fixed.

**Comment by Ruborcalor** [comment]
Great thanks, I should have made it clear that I was on the production server.
