### ISSUE TITLE
suggested data source for schedule of classes

### ISSUE THREAD

**Issue by pgrfe** [Aspine/aspine#138]
see tinyurl.com/crls2020 for a spreadsheet of classes scheduled at CRLS

**Comment by Ruborcalor** [comment]
Hello pgrfe thanks for opening this issue!

I think for identifying a student's schedule we currently pull data from the following view in Aspen.

![image](https://user-images.githubusercontent.com/47014480/94002843-733c9e00-fd68-11ea-8dfe-9132447de8bf.png)

Do you have an idea for how we could use the CRLS Schedule Search sheet to improve Aspine? One potential idea would be to just make more students aware of the sheet by putting a banner ad linking to it.

**Comment by pgrfe** [comment]
Cole I have not thought about how the full CRLS schedule of courses would
fit into Aspine.
I just wanted you to know about the existence of complete online datasheets
containing the full schedule of courses.
That could be connected to Aspine by simple cross-referencing the url, by
banner add or otherwise, as you say.
That is simple and easy to do on Aspine, I assume.

But the search sheet is very primitive; you and your friends could improve
it easily, I imagine.
You can copy the search sheet and make it better, or I can create a copy
editable on Google Sheets by your team.

Note that the search sheet is just search panels all pulling data from a
hidden sheet (view hidden sheets).
The hidden sheet is pulling from another public shared sheet that contains
data obtained from Cambridge.
The source is not real-time, but can be refreshed (not clear how often).

**Comment by pgrfe** [comment]
also the dataset was updated to September 23

**Comment by Ruborcalor** [comment]
Great sounds good. I currently don't have much time to work on improving the search sheet, but adding a banner should be relatively straightforward. This banner could be used for publicizing other CRLS clubs and activities as well. I wonder what @psvenk and @kdk1616 think.
