### ISSUE TITLE
Account for assignments being missing, exempt

### ISSUE THREAD

**Issue by Ruborcalor** [Aspine/aspine#14]
Currently the grading system either marks an assignment as having a grade, or being ungraded. It would be nice to acknowledge assignments that are labeled missing or exempt.

An additional improvement in this area would involve a page that lists all of a student's missing assignments.

**Comment by Ruborcalor** [comment]
Grading system now acknowledges missing and exempt assignments.

**Comment by Ruborcalor** [comment]
The system should flag missing assignments as having a score of 0 for grade calculation purposes, but does not do so currently.

**Comment by Ruborcalor** [comment]
Example: "Issue with missing assignments and how they factor into total grade and calculated grade. I currently have a missing assignment in TC Video Game Design and Development, but it is not being factored into the "Exams homework" section of my grade. Currently--without changing anything--my "Exams homework" grade is an 100, but it's actually a 71.4 in Aspen (it also shows the correct overall grade for the class at the described moment: 93.1). If I change the grade to a 0 out of 100 (which is what almost every other assignment is out of), the "Exams homework" grade drops to the correct grade of 71.4, but then says my calculated grade is an 87.4, when it is actually a 93.1."

**Comment by Ruborcalor** [comment]
Emphasis on this issue from the Community.

**Comment by psvenk** [comment]
@Ruborcalor What is the status of this issue?
