### ISSUE TITLE
Statistics for synthetic assignments

### ISSUE THREAD

**Issue by andOrlando** [Aspine/aspine#148]
Added assignments currently have an info button and try to display statistics but aren't real and don't have any statistics tied to them. They just display data from the last assignment whose statistics have been looked at. 

To fix this we should probably tag synthetic assignments somehow and just not show an info button on them. I'm currently thinking about adding the tabulator row index of the added assignments to a list to tag them.

**Comment by andOrlando** [comment]
I fixed and pushed(?) this as a branch, please excuse the sloppy use of github! I don't know if I should close this until @psvenk or someone reviews and commits my code to master?

**Comment by psvenk** [comment]
@andOrlando I see the changes - thank you for that. From <https://github.com/andOrlando/aspine/tree/removed-synthetic-statistics>, you should just be able to create a pull request to merge it into master, and I'll take a look.

**Comment by psvenk** [comment]
I am reopening this because the pull request is not yet merged; the convention is that we close issues when the associated pull requests are merged (adding "closes #148" to the description of the pull request causes this do be done automatically).
