### ISSUE TITLE
Collapse navigation bar into hamburger menu on small screens

### ISSUE THREAD

**Issue by psvenk** [Aspine/aspine#152]
Continuation of <https://github.com/Aspine/aspine/issues/144#issuecomment-715927138>. The tabs on the navigation bar take quite a bit of space on mobile displays, so we should collapse them into a hamburger menu depending on screen size (whether through CSS `@media` queries or through JavaScript).

<details>
<summary>Screenshot of the navigation header taking up 4 rows on a 640x1136 mobile screen</summary>

![IMG_5226](https://user-images.githubusercontent.com/45520974/97084859-bc8e4080-15e7-11eb-9ca9-6a757d27d63c.PNG)

</details>

**Comment by andOrlando** [comment]
We should probably rethink what we need there, like if the "gpa type" button is necessary or if the grade/calculated grade even has to be on that bar in the first place.

edit: comment no longer relevant
