### ISSUE TITLE
Changes in attendance marking system ("VP" - virtually present)

### ISSUE THREAD

**Issue by MohanMaker** [Aspine/aspine#159]
Aspen now reports your attendance as "VP" or virtually present each day. As a result, under Recent Events > Attendance in Aspine, there are a lot of attendance reports with no "Event." We should either make Aspine display VP for each of these attendance filings or make it ignore all reports of VP attendance since they are not very useful.

**Comment by tektaxi** [comment]
@MohanMaker Ok thanks, I'm working on that.
@psvenk what js file would that be in? I'm looking at scrape.js and it seems like it should be grabbing the VP code so I'm not sure why it's not working. Is there somewhere else I should be looking?

**Comment by tektaxi** [comment]
Nevermind, problem solved. I added it to my pull request (#161) along with the other recent attendance related fixes.
