### ISSUE TITLE
Close Aspen sessions when we are done with them

### ISSUE THREAD

**Issue by kdk1616** [Aspine/aspine#163]
The ICTS noticed increased sessions for student Aspen login, see if there is a way to close session on logout from Aspine.

**Comment by notrodes** [comment]
Scrape login returns aspen session data. We should save it in the aspine session.

**Comment by notrodes** [comment]
Look at the rest branch if you want to see this code, problem is solved.

**Comment by psvenk** [comment]
> Look at the rest branch if you want to see this code, problem is solved.

Problem *will be* solved (the rest branch is not yet ready for production)

**Comment by kdk1616** [comment]
Nice work, let’s discuss the rest branch and what else needs to be done at
the next meeting!!
