### ISSUE TITLE
General Aesthetics

### ISSUE THREAD

**Issue by Ruborcalor** [Aspine/aspine#18]
- [x] Are the "Add Assignment" and "Reset Changes" buttons too large?

**Comment by maxtkc** [comment]
How about this:

Assignment|Category|Score|Max Score|Percentage| :heavy_plus_sign:
---|---|---|---|---|---

Where the :heavy_plus_sign: is the `Add Assignment` button

and

Grades|Schedule|Quarter GPA: xx.xx<br>Calculated GPA: xx.xx :arrows_clockwise:|Logout
---|---|---|---

Where the :arrows_clockwise: is the `Reset Changes` button.

**Comment by maxtkc** [comment]
The + is good, but unicode has both of these builtin, and usually that is easier. Also, we could use fontawesome icons. The less extra dependencies the better.

**Comment by Ruborcalor** [comment]
Yes, agreed. I will look into fontawesome icons.

**Comment by maxtkc** [comment]
I think we can close because that is the only fix needed. For other aesthetics we can open specific issues.

**Comment by Ruborcalor** [comment]
Good close
