### ISSUE TITLE
Re-enable recent activity page for assignments

### ISSUE THREAD

**Issue by MohanMaker** [Aspine/aspine#180]
Aspen no longer displays recently inputted grades, but it could still be useful to have this feature. Aspine could look for assignments that have a recent "dateasgn" or "datedue", and display those. It could also display when term grades are posted.

**Comment by tektaxi** [comment]
@psvenk with the REST API that's been discovered, is there a way to reintroduce this easier? Or would we still have to build our own version?

**Comment by psvenk** [comment]
@tektaxi I don't think the REST API exposes the most recently added assignments (there is a place which seems to house it but is empty, just as in the desktop website), so we would need to reimplement this in any case.

**Comment by tektaxi** [comment]
@psvenk what do you think the best method of re-implementing would be? I'm happy to work on it but I'm not exactly sure how to go about doing it. I could change it to display the first few assignments from each class? But that wouldn't work with by date so I'm not sure.

**Comment by psvenk** [comment]
With the update to Aspen a few days ago, we can now re-enable recent activity in the same way that it used to work. There are some error messages currently being logged to the console by the recent activity code; we should investigate this and make sure that the recent activity works properly once we expose it in the UI.

**Comment by tektaxi** [comment]
aspen now has this again so we should make this a priority

**Comment by tektaxi** [comment]
We need to find a way to match the assignments in the recent array with the assignment in the class array. That way we can populate the max score and percentage field of the recentTable. If we match it we would also be able to display stats within the recent table as well

**Comment by jshaw-7** [comment]
the tabulator for recent activity disappears when you click on any cell. It also does not reappear after switching tabs or hitting the reset button, only when you first load the page.
