### ISSUE TITLE
Think about changing how GPA and quarter drop downs work

### ISSUE THREAD

**Issue by kdk1616** [Aspine/aspine#187]
- Should quarter dropdown be next to year?
- Should GPA be separated from quarter dropdown?
- Should GPA be put into classes table?
- Should we move the year dropdown so that it is clear that this only affects the "Grades" tab? (from #287)

<img width="1434" alt="Pasted Graphic copy" src="https://user-images.githubusercontent.com/31357347/100271495-8ebe5380-2f27-11eb-86e6-c74eb6bfe6bd.png">

**Comment by psvenk** [comment]
On hold until #152 is closed.

**Comment by psvenk** [comment]
The newer mockup that @kdk1616 put in #266: <img width="863" alt="IMG_1458" src="https://user-images.githubusercontent.com/31357347/107558289-95647a80-6ba8-11eb-82fc-44335d204b28.png">

**Comment by jshaw-7** [comment]
for 2.9.1- change dropdown menus to be "year select" and "quarter select", then on the next line (with reset and export buttons) add "Current Q1 GPA: 100" for example, with current/previous and the correct quarter. Move GPA Type button to the next line as well
