### ISSUE TITLE
Better response when user submits incorrect username and password.

### ISSUE THREAD

**Issue by Ruborcalor** [Aspine/aspine#19]
Currently a wrong username and password just kicks out the user. It'd be nice to display a message (or something of the sort) to let the user know what went wrong.

**Comment by MohanMaker** [comment]
To add to this, it seems that now if you enter to the wrong username and password, it brings you passed the login screen, but gets stuck in a forever loading loop.

**Comment by psvenk** [comment]
Duplicate of #226, which was fixed in #272.
