### ISSUE TITLE
Period numbering incorrect in clock

### ISSUE THREAD

**Issue by psvenk** [Aspine/aspine#199]
When a student has a different number of classes on black days than on silver days (particularly when there is an AM block in one but not the other), the period names do not update when switching between black and silver.

**Comment by notrodes** [comment]
I think this is best left until after the scraper is done.

**Comment by psvenk** [comment]
> I think this is best left until after the scraper is done.

@notrodes As I noted via the labels, this is a frontend issue. The current scraper used for the schedule is transplanted from the new (REST) scraper, so there is no remaining blocker on the backend.

**Comment by psvenk** [comment]
This bug actually extends to anyone with morning classes — because the index of a period is used to determine which period it is (e.g., the first period is assumed to be Period 1), the period numbering is wrong.
