### ISSUE TITLE
Shared Calendar for School Events

### ISSUE THREAD

**Issue by maxtkc** [Aspine/aspine#2]
Should Be
- Accessible to all users
- Moderated in some way
  - One moderater for every topic/calendar/channel
- Multiple categories/topics/calendars/channels
- Probably Google Calendar or similar
- Easy for non topic/calendar/channel operators to add events
- List associated with each user to show/hide categories/topics/calendars/channels

**Comment by notrodes** [comment]
Aspine does grades calenders do calenders
