### ISSUE TITLE
Fix highlighting in sidenav

### ISSUE THREAD

**Issue by psvenk** [Aspine/aspine#211]
There is no visual indication of the currently selected tab in the sidenav as there is when the sidenav is not open.

**Comment by notrodes** [comment]
also, the transition of the nav is soooo slooooooowwww moybe 0.2 sec is more appropriate, also also the css uses classes for everything not ids.

**Comment by jadebuckwalter** [comment]
@notrodes 0.2 sec is a little fast; 0.3 sec is better though.
