### ISSUE TITLE
Schedule is not displaying correctly because I don't have a second period

### ISSUE THREAD

**Issue by davidinholee** [Aspine/aspine#22]
![image](https://user-images.githubusercontent.com/26200438/53300166-7466bb80-3811-11e9-9aca-9570aff26ccf.png)

AP Bio should be my 3rd period class, Harvard the 4th, and PE Athletics after school.

**Comment by Ruborcalor** [comment]
Thank you for opening this issue; we will look into fixing it.

**Comment by Ruborcalor** [comment]
We have pushed a fix for this issue. Could you please let us know how your schedule is affected by it?
