### ISSUE TITLE
Remove Study support from Grades Tab

### ISSUE THREAD

**Issue by kdk1616** [Aspine/aspine#265]
-  Currently there are 4 study support classes

**Comment by jadebuckwalter** [comment]
@kdk1616 Another option is to keep the study support classes, but include some sort of information (whether that's the class, block number, etc) to differentiate between them. I get the sense that most teachers do not input grades for study support (in which case it is not useful to have study support in the grades tab) but that may not always be the case.

**Comment by tektaxi** [comment]
fixed in #280
