### ISSUE TITLE
Rearrange navbar to be more intuitive

### ISSUE THREAD

**Issue by tektaxi** [Aspine/aspine#266]
right now, switching quarters and the GPA functions are intertwined, which isn't very clear/intuitive. we should rearrange these buttons so it's more clear how to navigate the functions of Aspine.

**Comment by kdk1616** [comment]
Something like this:
<img width="863" alt="IMG_1458" src="https://user-images.githubusercontent.com/31357347/107558289-95647a80-6ba8-11eb-82fc-44335d204b28.png">

**Comment by jadebuckwalter** [comment]
There's already an issue for this: #187
