### ISSUE TITLE
Use CSS variables in getColor

### ISSUE THREAD

**Issue by tektaxi** [Aspine/aspine#284]
When your grade is 100 in a class, and you also have a calculated grade, the calculated grade shows up in black text. When in dark mode, this is a problem because it's really hard to read the black text on the dark grey background. It's a really specific scenario but worth the simple fix.

<img width="396" alt="Screen Shot 2021-03-24 at 4 47 45 PM" src="https://user-images.githubusercontent.com/45189395/112381187-ac76ac00-8cc0-11eb-91a4-041dd8498074.png">

**Comment by psvenk** [comment]
The core issue here is that `getColor` (in `extraFunctions.js`) contains hard-coded colors and uses black as a fallback; we should really be using CSS variables here.
