### ISSUE TITLE
Additional changes to snackbar

### ISSUE THREAD

**Issue by psvenk** [Aspine/aspine#285]
Split off from <https://github.com/Aspine/aspine/pull/222#pullrequestreview-614795474>.
- Deleting an assignment or clicking "undo" in the snackbar scrolls up to the top of the page
- Clicking anywhere on the snackbar other than the "undo" button dismisses the snackbar permanently
- Make Ctrl+Z more discoverable and make it use Command+Z on macOS

**Comment by andOrlando** [comment]
I believe the second bullet point should depend on the arguments to the snackbar, and I think @notrodes is touching up on some of the code. If my aspen fixes I can try to fix these after that

**Comment by tektaxi** [comment]
in production, the undo button doesn't work correctly, doesn't go away after clicking
