### ISSUE TITLE
Add text to clarify use of buttons

### ISSUE THREAD

**Issue by jadebuckwalter** [Aspine/aspine#318]
Particularly for the "export" and "reset" buttons, add text so that it is more clear what these buttons do. (This would only apply to desktop, not to mobile.)

**Comment by davidchengl74** [comment]
Hello, 
I can add the text to clarify use of buttons. 
I am doing this for my school assignment. 
The request needs to be merged for me to receive full credit. 
Can you kindly let me know if that works, and this can be assigned to me? 
Thank you very much.

**Comment by oneamanish** [comment]
see my pull req.
