### ISSUE TITLE
Fix lunch slider colors in dark mode

### ISSUE THREAD

**Issue by psvenk** [Aspine/aspine#320]
The lunch slider colors are not very good in dark mode.

![image](https://user-images.githubusercontent.com/45520974/140413480-45ddaa17-9ddc-4613-8306-8d9cd3acaedf.png)

**Comment by PoobyMalom** [comment]
Also center the B in its circle as its a little bit off center

**Comment by jshaw-7** [comment]
color is fixed here but the letters arent centered

<img width="280" alt="Screen Shot 2022-11-24 at 12 37 15 PM" src="https://user-images.githubusercontent.com/98419655/203841502-9bfd968a-8ae8-47ff-b727-0d0fb6a855f7.png">
