### ISSUE TITLE
Box plot figures are rounded/inaccurate

### ISSUE THREAD

**Issue by psvenk** [Aspine/aspine#34]
I noticed that the box plot rounds all figures, which results in inaccurate results. For example, in the below screenshots, Aspine shows me as having the highest grade in the class on this assignment and reports the median as both 17 (in the box plot) and 18 (below the box plot), when it is actually 18.5. If Aspine stored all values internally as floating points and displayed them with an accuracy of 2 or 3 decimal places, this issue would be solved.

Screenshot of Aspine:
<img src="https://user-images.githubusercontent.com/45520974/55117093-f1f74300-50bf-11e9-8adc-f2a0b3155ee1.png">
Screenshot of Aspen:
<img src="https://user-images.githubusercontent.com/45520974/55117094-f3287000-50bf-11e9-8a4c-f4c08c6c4e93.png" height="300">

**Comment by psvenk** [comment]
This is actually more than just integer rounding. On another assignment (in another class), the median score is 93 in the box plot and 100 under the box plot. These two scores are almost a letter grade apart.
![Screenshot at 2019-03-27 18-51-29](https://user-images.githubusercontent.com/45520974/55117538-9c239a80-50c1-11e9-99ac-a9f1d9ca9d3a.png)

**Comment by Ruborcalor** [comment]
Thank you for opening this issue. I will look into resolving it. The screenshots are very helpful.

**Comment by Ruborcalor** [comment]
I have resolved this issue in the Tabulator and Plotly Improvements branch.
