### ISSUE TITLE
Attendance Loads Incorrectly

### ISSUE THREAD

**Issue by tektaxi** [Aspine/aspine#342]
On the current version of Aspine attendance information only populates the attendance table when you immediately click the attendance tab in the initial loading cycle of Aspine. If you let any other tab load first and then click attendance, it doesn't have any information in the attendance tab. 

Attendance loaded first; normal.
<img width="1415" alt="Screen Shot 2022-10-01 at 2 03 17 PM" src="https://user-images.githubusercontent.com/45189395/193422359-6020a68d-a9e4-449e-8ea8-5a9169bac590.png">

Attendance loaded second; doesn't populate the table.
<img width="1436" alt="Screen Shot 2022-10-01 at 2 03 53 PM" src="https://user-images.githubusercontent.com/45189395/193422375-c4b8af40-d801-407a-a688-e8c4108833ee.png">

**Comment by jshaw-7** [comment]
this fixed itself with recent activity!
