### ISSUE TITLE
Move JavaScript out of home.html

### ISSUE THREAD

**Issue by psvenk** [Aspine/aspine#45]
This should be pretty much self-explanatory. Having a lot of JavaScript in the `home.html` file decreases the readability of the code (scripting is mixed in the middle of markup). I suggest either moving this logic to a `home.js` file or integrating it in another JavaScript file used only by `home.html` (I don't know—I have not studied the code enough).

**Comment by psvenk** [comment]
Also, having indented JavaScript in indented HTML causes some lines of code being indented so much that it affects readability, such as [lines 307 to 319](https://github.com/maxtkc/aspine/blob/433aea935ef57c3e73dc7b9cc3211f429af9b9af/public/home.html#L307-L319):
```js
████████████████████████████████████████████████████████████████
								shapes: [
									{
										type: 'line',
										x0:score,
										y0:-0.5,
										x1: score,
										y1: 0.5,
										line: {
											color: '#00551C',
											width: 3,
										},
									}
								],
```
![image](https://user-images.githubusercontent.com/45520974/55596100-fc938700-5714-11e9-93a4-9db39c7df4b7.png)
That is 64 characters of indentation (actually 16 literal characters, because it is 16 tabs, but it takes up as much space as 64 normal characters).

**Comment by Ruborcalor** [comment]
Nice :+1:
