### ISSUE TITLE
Chat Room(s)

### ISSUE THREAD

**Issue by maxtkc** [Aspine/aspine#5]
Add some sort of irc-like chat.
Hopefully
- Safe
  - Operators can mute/disable users
- Fast

**Comment by maxtkc** [comment]
Options:
- xmpp
  - [list of clients](https://xmpp.org/software/clients.html) - we would use a browser client
- irc
  - [Kiwi](https://kiwiirc.com/)
  - [Mibbit](https://mibbit.com/)
  - Uglier and harder to use, but often more powerful
- Other...

**Comment by Ruborcalor** [comment]
Those look pretty cool. I also saw The Lounge
https://thelounge.chat/

**Comment by Ruborcalor** [comment]
converse.js looks nice but we should talk in person cause I don't
completely understand

**Comment by Ruborcalor** [comment]
Also schedule looks really nice, but I still think it will be too wide to
show up on a phone

**Comment by maxtkc** [comment]
Ok, we can make the black/silver a tabbed kind of thing. -- in the future use issue #1 for that topic.

The lounge looks good. I hope we can find something that uses irc protocol but is button based, not command based.

Also, if you reply by email, try to delete any extra stuff from previous emails (`ctrl a`, `backspace`, and then your message)

**Comment by maxtkc** [comment]
I like how [JSXC](https://www.jsxc.org/) looks. Quite light and modular. It will be easier and more configurable than using an iframe. If we want it to auto-login with their aspen account, then it will be nice.

**Comment by Ruborcalor** [comment]
Yes that looks really smooth.
Lmao "Make XMPP Great Again!"

Also curious why do you like to delete extra stuff from previous emails?

**Comment by psvenk** [comment]
Because we are now hosted on school servers, this would be infeasible to implement due to anti–cyber-bullying regulations.
