### ISSUE TITLE
Different Colors for Different Percentages Within a Letter Grade

### ISSUE THREAD

**Issue by Ruborcalor** [Aspine/aspine#50]
Differentiate, for example, between an 80% and an 88%.

Preferably via a gradient.

**Comment by notrodes** [comment]
Is this needed?

**Comment by andOrlando** [comment]
> Is this needed?

of course it is. It's a very important and key change.

**Comment by psvenk** [comment]
We voted this down in December (see <https://github.com/Aspine/aspine/pull/150#issuecomment-742821033>).
