### ISSUE TITLE
Mean in box plot is sometimes yellow on white

### ISSUE THREAD

**Issue by psvenk** [Aspine/aspine#59]
When opening a box plot for an assignment, the colors which the "Mean" bar can take on (depending on the mean grade for the assignment) seem to be different from the colors defined in the color palette. While this would normally be just an aesthetic inconsistency, I noticed that when the mean grade is a C, the mean bar becomes yellow and the word "Mean" becomes hard to see. This issue can be fixed by adhering to the color palette for the colors which the "Mean" bar can take on.

![image](https://user-images.githubusercontent.com/45520974/56539685-9a1ff080-6534-11e9-9b42-b67a2b2fd0da.png)

**Comment by Ruborcalor** [comment]
Thanks for creating this issue. The colors that the "Mean" bar can take on are indeed different. The thinking at the time was that this slight tone difference would allow users to distinguish between the "Mean" and "Your Score" bars, but it is a problem that it becomes unreadable when the mean grade is a C. 

I have shifted the color of the "Mean" bar to use the same palette as "Your Score".

Any suggestions for helping the user distinguish between "Your Score" and "Mean"? Or is it something now worth worrying about?

**Comment by psvenk** [comment]
Instead of changing the brightness, you could decrease the saturation for "Mean". This is not very easy to do with RGB, but you can convert RGB to HSL (where S = "Saturation") by adjusting the second slider at <http://hslpicker.com/> and then convert back to RGB.

**Comment by psvenk** [comment]
Here is a sample color palette for the "Mean" bar, where I decreased saturation by 20 percentage points and increased luminosity by 10 percentage points (using the hex colors for "Orange" and "Red" from <https://developer.mozilla.org/en-US/docs/Web/CSS/color_value>)

| Grade Range   | Letter        | Color |
| :-----------  |:--------------|:------|
| 96.5 - 100    | A+            |#3d995c|
| 92.5 - 96.4   | A             |#3d995c|
| 89.5 - 92.4   | A-            |#3d995c|
| 86.5 - 89.4   | B+            |#a3a3f5|
| 82.5 - 86.4   | B             |#a3a3f5|
| 79.5 - 82.4   | B-            |#a3a3f5|
| 76.5 - 79.4   | C+            |#eba947|
| 72.5 - 76.4   | C             |#eba947|
| 69.5 - 72.4   | C-            |#eba947|
| 66.5 - 69.4   | D+            |#ebb147 |
| 62.5 - 66.4   | D             |#ebb147 |
| 59.5 - 62.4   | D-            |#ebb147 |
| 0    - 59.4   | F             |#eb4747    |

**Comment by Ruborcalor** [comment]
Thank you! I will add this color palette to README and incorporate it into the "Mean" bar coloring.
