### ISSUE TITLE
Wiki?!?!??!

### ISSUE THREAD

**Issue by notrodes** [Aspine/aspine#65]
@psvenk Please open up wiki!!!!

**Comment by psvenk** [comment]
@notrodes Are you able to edit it now? https://github.com/Aspine/aspine/wiki

![image](https://user-images.githubusercontent.com/45520974/67004536-86ea7980-f0ae-11e9-82a6-01791361c248.png)

I unchecked "Restrict editing to users in teams with push access only" in the settings and made an initial commit for the wiki.
