### ISSUE TITLE
Add an instructions page

### ISSUE THREAD

**Issue by Ruborcalor** [Aspine/aspine#76]
Add an "Instructions" page with advice for how to best take advantage of Aspine's features. The features are sometimes unclear to new users. This page could potentially even take the form of a video.

Potential instructions:

* On the recent activity page: Using the switch to view "Assignments" or "Attendance"
* On the schedule page: using the switch to view "black" days or "silver" days
* On the grades page, taking advantage of the "info" icon for viewing statistical data and teacher feedback.
* How to use the grade prediction feature (eventually including the percent test corrections feature from #72)

**Comment by psvenk** [comment]
Perhaps this could be merged with #79 as a guided tour?

**Comment by andOrlando** [comment]
I could write another tab as long as someone checks my code later for efficiency and convention, but I don't think I could do a guided tour.
