### ISSUE TITLE
Only first page of PDFs shown in Reports tab

### ISSUE THREAD

**Issue by psvenk** [Aspine/aspine#88]
If possible, a simple fix would be just to use the controls provided by pdf.js instead of drawing our own controls.

**Comment by notrodes** [comment]
Closing, we no longer have this feature.

**Comment by psvenk** [comment]
This feature is still pertinent. This issue now depends on the reports feature working again.

**Comment by psvenk** [comment]
The fix to make the PDF viewer work again, as well as the changes in this issue and #89, will be addressed when #103 is merged.

**Comment by psvenk** [comment]
Fixed in #103.
