### ISSUE TITLE
Fullscreen does not work in Reports tab

### ISSUE THREAD

**Issue by psvenk** [Aspine/aspine#89]
The PDF viewer frame retains its aspect ratio and thus only takes up about 1/3 of the screen on most monitors.

**Comment by notrodes** [comment]
Closing, we no longer have this feature.

**Comment by Ruborcalor** [comment]
We shouldn't close the issue if it relates to a feature that we eventually want to bring back.

**Comment by psvenk** [comment]
The fix to make the PDF viewer work again, as well as the changes in this issue and #88, will be addressed when #103 is merged.

**Comment by notrodes** [comment]
With re-implementation has this been fixed?

**Comment by psvenk** [comment]
This has been fixed in #103.
