### ISSUE TITLE
Figure out what lunch students have

### ISSUE THREAD

**Issue by kdk1616** [Aspine/aspine#95]
* [x] Use period three class code to determine what lunch students have
* [x] Show this on schedule

**Comment by notrodes** [comment]
What is the status of this? I thought this was implemented

**Comment by psvenk** [comment]
The current implementation has some flaws. We will need to re-evaluate after some time.

**Comment by andOrlando** [comment]
Not entirely sure if we can be 100% accurate. Don't some classes not conform to the general lunch thing?

**Comment by psvenk** [comment]
The goal is not to be 100% accurate but to go by the policy set by the school, which most classes follow. In any case, this is on hold until we reopen in person.

**Comment by psvenk** [comment]
This is no longer on hold because the new schedule includes two lunches (Lunch A and Lunch B), so we should try to get this in version 2.8.0 along with #288.

**Comment by psvenk** [comment]
This is on hold until the school determines how Lunch A and Lunch B will be assigned.

**Comment by psvenk** [comment]
Lunch assignments were announced today, so this was implemented in 84fc380fcd as part of #294.
