### ISSUE TITLE
Clean up code

### ISSUE THREAD

**Issue by psvenk** [Aspine/aspine#96]
Much of the codebase is poorly formatted, with inconsistent indentation and disorganization in JavaScript files. I propose that we temporarily freeze the repository at some point (stop accepting any new commits or pull requests until a set later date) in order to improve the formatting on both the frontend and the backend. The improvements may include refactoring in addition to improving formatting.

**Comment by notrodes** [comment]
Just a note in the future we should version using package.json

**Comment by notrodes** [comment]
I've been working...

**Comment by psvenk** [comment]
Closed in #108.
